{
 "title": "Metrics for Prediction",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "phnf", "query": { "query": "scrape_duration_seconds" } },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "memtyp",
    "query": {
     "query": "phoenix_memory_pool_create_count"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "phoenix_memory_pool_create_count"
    }
   },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs, instance)"
    }
   },
   {
    "name": "ProcessMemType",
    "query": {
     "query": "label_values(namedprocess_namegroup_memory_bytes, memtype)"
    }
   },
   {
    "name": "subscriber_state",
    "query": {
     "query": "label_values(open5G_bt_subscriber_count,subscriber_state)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(open5G_bt_subscriber_operation_timing, operation)"
    }
   },
   {
    "name": "operation_timing_type",
    "query": {
     "query": "label_values(open5G_bt_subscriber_operation_timing, type)"
    }
   },
   { "name": "pool", "query": { "query": "phoenix_memory_alloc_count" } }
  ]
 },
 "panels": [
  { "title": "AMF Memory Usage 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "AMF Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CM Wasted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_wasted_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
    }
   ]
  },
  {
   "title": "CM Allocated Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_allocated_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"} / 1048576"
    }
   ]
  },
  {
   "title": "CM Allocation Count Total ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_allocation_count_total{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
    }
   ]
  },
  {
   "title": "CM Total MB Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(phoenix_memory_cm_allocated_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Max Used Chunks Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_max_used_chunks_per_pool_count{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
    }
   ]
  },
  {
   "title": "Chunk Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_chunk_count_total{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
    }
   ]
  },
  {
   "title": "CM Used Chunk Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "phoenix_memory_cm_used_chunk_count{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
    }
   ]
  },
  {
   "title": "Metrics by Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Server Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "http_server_request_count{instance=~\"$instance\",phnf=~\"$phnf\"}"
      }
     ]
    },
    {
     "title": "Http Client Response Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "http_client_response_count{instance=~\"$instance\",phnf=~\"$phnf\"}"
      }
     ]
    },
    {
     "title": "Chunk Count Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "phoenix_memory_cm_chunk_count_total{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
      }
     ]
    },
    {
     "title": "CM Total MB Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "(phoenix_memory_cm_allocated_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"} - phoenix_memory_cm_wasted_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}) / 1000000"
      }
     ]
    },
    {
     "title": "Phoenix Process Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{memtype=~\"resident\",groupname=~\"$processes\"}",
       "legendFormat": "{{phnf}}, {{groupname}}"
      }
     ]
    },
    {
     "title": "CM Used Chunk Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "phoenix_memory_cm_used_chunk_count{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}"
      }
     ]
    },
    {
     "title": "Rate of  Non-Voluntary Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "http_client_request_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "http_client_request_count{instance=~\"$instance\",phnf=~\"$phnf\"}"
      }
     ]
    },
    {
     "title": "Top processes by Minor Page Faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Subscriber_Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "open5G_bt_subscriber_count{component=\"bt5g\", instance=\"192.168.254.120:9888\", job=\"phoenix\", phnf=\"bt\", subscriber_state=\"$subscriber_state\"}"
      }
     ]
    },
    {
     "title": "CPU Usage from System View",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\", mode='system'}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Subscriber Operation Timing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "open5G_bt_subscriber_operation_timing{instance=\"192.168.254.120:9888\", job=\"phoenix\", operation=\"$operation\", phnf=\"bt\", type=\"avg\"}"
      }
     ]
    },
    {
     "title": "Minor Page Faults by Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])"
      }
     ]
    },
    {
     "title": "Phoenix Process Memory Usage per Subscriber",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{memtype=~\"resident\",groupname=~\"$processes\"} / 594",
       "legendFormat": "{{phnf}}, {{groupname}}"
      }
     ]
    },
    {
     "title": "Thread count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_threads{groupname=~\"$processes\"}",
       "legendFormat": "{{groupname}})"
      }
     ]
    },
    {
     "title": "Processes by Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_open_filedesc{groupname=~\"$processes\"}",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes waiting on IO",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[5m])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Phoenix Process In Sleeping State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "max_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Sleeping\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Sleeping\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes by Major Page Faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Minor Page Faults by Counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Top processes by Minor Page Faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes by Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(max_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\"}[5m]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage from System View",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\"}[$__rate_interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\"}[1m])",
       "legendFormat": "{{ctxswitchtype}} ctx switches per min ({{groupname}})"
      }
     ]
    },
    {
     "title": "Processes by Voluntary Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[5m])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Processes by  Non-Voluntary Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[5m])",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory And Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "CM Total MB Used",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "(phoenix_memory_cm_allocated_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"} - phoenix_memory_cm_wasted_bytes{instance=~\"$instance\",memtype=~\"$memtyp\",phnf=~\"$phnf\"}) / 1000000"
      }
     ]
    },
    {
     "title": "Phoenix Process Memory Usage",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{memtype=~\"resident\",groupname=~\"$processes\"}",
       "legendFormat": "{{phnf}}, {{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_threads{groupname=~\"$processes\"}",
       "legendFormat": "{{groupname}})"
      }
     ]
    }
   ]
  }
 ]
}